import { useState } from 'react'
import { api } from '../api'

const SECTIONS = [
  { num: 1, title: 'Executive Summary',             note: 'Generated by Report Narrator — review and mark up' },
  { num: 2, title: 'Engagement Overview',           note: 'Auto-generated from engagement record' },
  { num: 3, title: 'Operational Maturity Overview', note: 'Auto-generated from signal domains' },
  { num: 4, title: 'Domain Analysis',               note: 'Auto-generated from findings by domain' },
  { num: 5, title: 'Root Cause Analysis',           note: 'Auto-generated from finding root causes' },
  { num: 6, title: 'Economic Impact Analysis',      note: 'Auto-generated from finding economic impact' },
  { num: 7, title: 'Improvement Opportunities',     note: 'Auto-generated from recommendations' },
  { num: 8, title: 'Transformation Roadmap',        note: 'Auto-generated from roadmap items by phase' },
]

export default function ReportPanel({ engagementId }) {
  const [downloading, setDownloading]       = useState(false)
  const [downloadError, setDownloadError]   = useState(null)

  const handleDownload = async () => {
    setDownloading(true)
    setDownloadError(null)
    try {
      const blob = await api.reporting.downloadReport(engagementId)
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href     = url
      a.download = `OPD_Transformation_Roadmap_${engagementId}.docx`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      setDownloadError(err.message)
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-sm font-semibold text-gray-900">OPD Transformation Roadmap Report</h2>
          <p className="text-xs text-gray-500 mt-1">
            Word document generated from engagement data. Section 1 requires manual completion.
          </p>
        </div>
        <button
          onClick={handleDownload}
          disabled={downloading}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50 transition-colors"
        >
          {downloading ? 'Generating...' : 'Download Report'}
        </button>
      </div>

      {downloadError && (
        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-xs text-red-700">
          {downloadError}
        </div>
      )}

      <div className="space-y-2">
        {SECTIONS.map(s => (
          <div key={s.num}
            className="flex items-start gap-4 p-3 border border-gray-100 rounded-lg">
            <span className="text-xs font-mono text-gray-400 w-6 shrink-0 pt-0.5">{s.num}</span>
            <div>
              <p className="text-sm font-medium text-gray-900">{s.title}</p>
              <p className="text-xs text-gray-400 mt-0.5">{s.note}</p>
            </div>
            {s.num === 1 ? (
              <span className="ml-auto text-xs bg-yellow-100 text-yellow-700 px-2 py-0.5 rounded">Manual</span>
            ) : (
              <span className="ml-auto text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded">Auto</span>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
